import { resolveProductoConfiguracion } from 'utilities/productos';
import { normalizeEvaluacionConsumoState } from './status';

export const buildEvaluacionConsumoPrintView = (record) => {
  if (!record) return null;

  const productoRange = resolveProductoConfiguracion(record?.producto, {
    tipoFrecuencia: record?.tipo_frecuencia,
    monto: record?.monto,
    numeroCuotas: record?.numero_cuotas,
  });

  return {
    id: record.id,
    estado: normalizeEvaluacionConsumoState(record.estado),
    fechaEvaluacion: record.fecha_evaluacion
      ? new Date(record.fecha_evaluacion).toLocaleString('es-PE')
      : 'N/A',
    agencia: record?.sede?.nombre || 'N/A',
    usuario: record?.usuario?.username || 'N/A',
    perfil: record?.rol?.nombre || 'N/A',
    decisionComentario: record.decision_comentario || 'N/A',
    cliente: record.solicitante_nombre_snapshot,
    dni: record.solicitante_dni_snapshot,
    direccion: record.direccion_snapshot || 'N/A',
    categoria: record?.categoria?.nombre || 'N/A',
    antiguedadLaboral: record.antiguedad_laboral_texto || 'N/A',
    planInversion: record?.plan_inversion || 'N/A',
    moneda: record?.moneda?.nombre || 'N/A',
    monto: record.monto,
    clasePrestamo: record.clase_prestamo_snapshot,
    tipoFrecuencia: record.tipo_frecuencia,
    valorFrecuencia: record.valor_frecuencia,
    numeroCuotas: record.numero_cuotas,
    propuesta: record.propuesta,
    cuota: record.cuota,
    rangoTasa: productoRange?.label || 'N/A',
    producto: record?.producto?.nombre || 'N/A',
    expuestoRcc: record.expuesto_rcc ? 'SI' : 'NO',
    tasaSolicitada: record.tasa_interes_solicitada,
    discrecionalidad: record?.nivel_discrecionalidad_resuelto?.rol_autorizador?.nombre || 'SIN REGLA APLICABLE',
    motivos: record.motivos || 'N/A',
    ingresoTotal: record.ingreso_total,
    montoMaximoTotal: record.monto_maximo_total,
    ingresos: record.ingresos || [],
    otrosIngresosSector: record.otros_ingresos_sector_snapshot || 'N/A',
    otrosIngresosActividad: record.otros_ingresos_actividad_snapshot || record.otros_ingresos_tipo_negocio || 'N/A',
    otrosIngresosMargenMaximo: record.otros_ingresos_margen_maximo_snapshot,
    otrosIngresosTipoNegocio: record.otros_ingresos_tipo_negocio || 'N/A',
    otrosIngresosVentas: record.otros_ingresos_ventas,
    otrosIngresosCosto: record.otros_ingresos_costo,
    otrosIngresosGasto: record.otros_ingresos_gasto,
    otrosIngresosUtilidad: record.otros_ingresos_utilidad,
    ingresoNeto: record.ingreso_neto,
    sumatoriaCuotas: record.sumatoria_cuotas,
    deudaTotal: record.deuda_total,
    numeroIfis: record.numero_ifis,
    apalancamiento: record.apalancamiento,
    capacidadEndeudamiento: record.capacidad_endeudamiento,
    boletaBasica: record.boleta_basica,
    boletaVariableMes1: record.boleta_variable_mes_1,
    boletaVariableMes2: record.boleta_variable_mes_2,
    boletaVariableMes3: record.boleta_variable_mes_3,
    gastoAlimentacion: record.gasto_alimentacion,
    gastoServicios: record.gasto_servicios,
    gastoEducacion: record.gasto_educacion,
    gastoMovilidad: record.gasto_movilidad,
    gastoImprevistos: record.gasto_imprevistos,
    gastoSubtotal: record.gasto_subtotal,
    gastoObligaciones: record.gasto_obligaciones,
    gastoOtrosEgresos: record.gasto_otros_egresos,
    criterioEntorno: record.criterio_entorno || 'N/A',
    criterioDireccion: record.criterio_direccion || 'N/A',
    criterioCapacidadPago: record.criterio_capacidad_pago || 'N/A',
    criterioMoralPago: record.criterio_moral_pago || 'N/A',
    criterioSituacionFinanciera: record.criterio_situacion_financiera || 'N/A',
    criterioPlanInversion: record.criterio_plan_inversion || 'N/A',
    criterioColaterales: record.criterio_colaterales || 'N/A',
    criterioCondiciones: record.criterio_condiciones || 'N/A',
  };
};